package com.asdc.pawpals.utils;

/**
 * The MailTemplates class provides static StringBuilder objects that represent different email templates for the application.
 */
public class MailTemplates {

    private static final StringBuilder REGISTRATION_SUCCESFUL = new StringBuilder();

    private static final StringBuilder PET_OWNER_REGISTRATION_SUCCESSFUL = new StringBuilder();

    private static final StringBuilder VET_REGISTRAION_CONFIRMATION = new StringBuilder();

    private static final StringBuilder VET_REGISTRATION_APPROVED = new StringBuilder();

    private static final StringBuilder VET_REGISTRATION_REJECTED = new StringBuilder();

    private static final StringBuilder APPOINTMENT_CONFIRMATION = new StringBuilder();

    private static final StringBuilder APPOINTMENT_CANCEL = new StringBuilder();

    public static String getRegistrationSuccessfulString() {
        REGISTRATION_SUCCESFUL.append("<html>")
                .append("  <head>")
                .append("    <title>Welcome to Pawpals!</title>")
                .append("    <style>")
                .append("      body {")
                .append("        background-image: url('https://images.pexels.com/photos/4587979/pexels-photo-4587979.jpeg?auto=compress&cs=tinysrgb&w=600');")
                .append("        background-size: cover;")
                .append("        font-family: Arial, sans-serif;")
                .append("        text-align: center;")
                .append("      }")
                .append("")
                .append("      .container {")
                .append("        background-color: #fff;")
                .append("        border-radius: 5px;")
                .append("        box-shadow: 0 2px 5px rgba(0, 0, 0, .3);")
                .append("        max-width: 500px;")
                .append("        margin: 50px auto;")
                .append("        padding: 20px;")
                .append("      }")
                .append("")
                .append("      h1 {")
                .append("        color: #f57c00;")
                .append("      }")
                .append("")
                .append("      p {")
                .append("        font-size: 18px;")
                .append("        line-height: 1.5;")
                .append("        margin-bottom: 20px;")
                .append("      }")
                .append("")
                .append("      a {")
                .append("        color: #fff;")
                .append("        background-color: #f57c00;")
                .append("        border-radius: 3px;")
                .append("        display: inline-block;")
                .append("        font-size: 16px;")
                .append("        font-weight: bold;")
                .append("        padding: 10px 20px;")
                .append("        text-decoration: none;")
                .append("        transition: background-color .3s ease;")
                .append("      }")
                .append("")
                .append("      a:hover {")
                .append("        background-color: #e65100;")
                .append("      }")
                .append("")
                .append("      .footer {")
                .append("        font-size: 14px;")
                .append("        color: #999999;")
                .append("        text-align: center;")
                .append("        margin-top: 20px;")
                .append("        padding-top: 20px;")
                .append("        border-top: 1px solid #CCCCCC;")
                .append("      }")
                .append("")
                .append("      .footer p {")
                .append("        margin: 0;")
                .append("        padding: 0;")
                .append("      }")
                .append("    </style>")
                .append("  </head>")
                .append("  <body>")
                .append("    ")
                .append("    <div class=\"container\">")
                .append("      <h1>Welcome to Pawpals!</h1>")
                .append("      <p>Thank you for registering with Pawpals. Your account has been created successfully.</p>")
                .append("      ")
                .append("      <div class=\"footer\">")
                .append("        <br>")
                .append("        <p>© PawPals 2023. All rights reserved.</p>")
                .append("      </div>")
                .append("    </div>")
                .append("  </body>")
                .append("")
                .append("</html>");

        return REGISTRATION_SUCCESFUL.toString();
    }

    public static String getPetOwnerRegistrationSuccessfulString(String petOwnerName, String linkToLoginPage) {
        return PET_OWNER_REGISTRATION_SUCCESSFUL.append("<html>")
                .append("")
                .append("<head>")
                .append("  <title>PawPals - Pet Owner Registration Confirmation</title>")
                .append("  <style>")
                .append("    body {")
                .append("      font-family: Arial, sans-serif;")
                .append("      background-color: #f5f5f5;")
                .append("      margin: 0;")
                .append("      padding: 0;")
                .append("    }")
                .append("")
                .append("    .container {")
                .append("      max-width: 600px;")
                .append("      margin: 0 auto;")
                .append("      background-color: #ffffff;")
                .append("      padding: 20px;")
                .append("      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);")
                .append("      border-radius: 5px;")
                .append("      margin-top: 30px;")
                .append("    }")
                .append("")
                .append("    h1 {")
                .append("      color: #003399;")
                .append("      font-size: 28px;")
                .append("      margin-bottom: 20px;")
                .append("      display: flex;")
                .append("      justify-content: center;")
                .append("    }")
                .append("")
                .append("    p {")
                .append("      font-size: 16px;")
                .append("      line-height: 1.5;")
                .append("      margin-bottom: 15px;")
                .append("    }")
                .append("    ")
                .append("    .button-outer{")
                .append("      display: flex;")
                .append("      justify-content:center;")
                .append("    }")
                .append("")
                .append("    .button {")
                .append("      ")
                .append("      background-color: #003399;")
                .append("      color: #ffffff;")
                .append("      padding: 10px 20px;")
                .append("      border-radius: 5px;")
                .append("      text-decoration: none;")
                .append("      font-size: 16px;")
                .append("      margin-top: 20px;")
                .append("    }")
                .append("")
                .append("    .button:hover {")
                .append("      background-color: #002266;")
                .append("    }")
                .append("")
                .append("    .logo {")
                .append("      display: block;")
                .append("      margin: 20px 0;")
                .append("    }")
                .append("")
                .append("    .footer {")
                .append("      margin-top: 30px;")
                .append("      font-size: 14px;")
                .append("      color: #999999;")
                .append("      text-align: center;")
                .append("    }")
                .append("")
                .append("    .footer a {")
                .append("      color: #999999;")
                .append("      text-decoration: none;")
                .append("    }")
                .append("")
                .append("    .footer a:hover {")
                .append("      text-decoration: underline;")
                .append("    }")
                .append("  </style>")
                .append("</head>")
                .append("")
                .append("<body>")
                .append("  <div class=\"container\">")
                .append("")
                .append("    <h1>Registration Confirmation</h1>")
                .append("    <p>Dear ")
                .append(petOwnerName)
                .append(",</p>")
                .append("    <p>Thank you for registering as a pet parent with PawPals. Your account has been created and is now ready for use.</p>")
                .append("    <p>You can log in to your account using your email address and the password you provided during registration.</p>")
                .append("    <div class=\"button-outer\">")
                .append("    <a href=\"")
                .append(linkToLoginPage)
                .append("\" class=\"button\">Log In to Your Account</a>")
                .append("    </div>")
                .append("    <p>If you have any questions or concerns, please don't hesitate to contact us at <strong>support.pawpals@gmail.com</strong>.</p>")
                .append("    <div class=\"footer\">")
                .append("      <p>Thank you for choosing PawPals for your pet's veterinary care.</p>")
                .append("      <p>© PawPals 2023. All rights reserved.</p>")
                .append("")
                .append("    </div>")
                .append("  </div>")
                .append("</body>")
                .append("")
                .append("</html>").toString();
    }

    public static String getVetRegistrationConfirmationString(String vetName) {
        return VET_REGISTRAION_CONFIRMATION.append("<html>")
                .append("")
                .append("<head>")
                .append("")
                .append("  <title>PawPals - Vet Registration Confirmation</title>")
                .append("<style>")
                .append("  body {")
                .append("    font-family: Arial, sans-serif;")
                .append("    background-color: #f5f5f5;")
                .append("    margin: 0;")
                .append("    padding: 0;")
                .append("  }")
                .append("")
                .append("  .container {")
                .append("    max-width: 600px;")
                .append("    margin: 0 auto;")
                .append("    background-color: #ffffff;")
                .append("    padding: 20px;")
                .append("    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);")
                .append("    border-radius: 5px;")
                .append("    margin-top: 30px;")
                .append("  }")
                .append("")
                .append("  h1 {")
                .append("    color: #003399;")
                .append("    font-size: 28px;")
                .append("    margin-bottom: 20px;")
                .append("    display: flex;")
                .append("    justify-content: center;")
                .append("  }")
                .append("")
                .append("  p {")
                .append("    font-size: 16px;")
                .append("    line-height: 1.5;")
                .append("    margin-bottom: 15px;")
                .append("  }")
                .append("")
                .append("  .button {")
                .append("    display: inline-block;")
                .append("    background-color: #003399;")
                .append("    color: #ffffff;")
                .append("    padding: 10px 20px;")
                .append("    border-radius: 5px;")
                .append("    text-decoration: none;")
                .append("    font-size: 16px;")
                .append("    margin-top: 20px;")
                .append("  }")
                .append("")
                .append("  .button:hover {")
                .append("    background-color: #002266;")
                .append("  }")
                .append("")
                .append("  .logo {")
                .append("    display: block;")
                .append("    margin: 20px 0;")
                .append("  }")
                .append("")
                .append("  .footer {")
                .append("    margin-top: 30px;")
                .append("    font-size: 14px;")
                .append("    color: #999999;")
                .append("    text-align: center;")
                .append("  }")
                .append("")
                .append("  .footer a {")
                .append("    color: #999999;")
                .append("    text-decoration: none;")
                .append("  }")
                .append("")
                .append("  .footer a:hover {")
                .append("    text-decoration: underline;")
                .append("  }")
                .append("</style>")
                .append("</head>")
                .append("")
                .append("<body>")
                .append("  <div class=\"container\">")
                .append("    <h1>Registration Confirmation</h1>")
                .append("    <p>Dear ")
                .append(vetName)
                .append(",</p>")
                .append("    <p>Thank you for registering as a veterinarian with PawPals. Your registration has been received and is currently being reviewed by our team.</p>")
                .append("    <p>Please note that your account will remain inactive until it has been authenticated by the admin. We will send you another email as soon as your account has been activated.</p>")
                .append("    <p>If you have any questions or concerns, please don't hesitate to contact us at <strong>support.pawpals@gmail.com</strong>.</p>")
                .append("    <div class=\"footer\">")
                .append("      <p>Thank you for choosing PawPals for your veterinary practice.</p>")
                .append("      <p>© PawPals 2023. All rights reserved.</p>")
                .append("")
                .append("    </div>")
                .append("  </div>")
                .append("</body>")
                .append("")
                .append("</html>").toString();
    }

    public static String getVetApprovedMessageString(String vetName, String linkToLoginPage) {
        return VET_REGISTRATION_APPROVED.append("<html>")
                .append("")
                .append("<head>")
                .append("  <title>PawPals - Vet Registration Approved</title>")
                .append("  <style>")
                .append("    body {")
                .append("      font-family: Arial, sans-serif;")
                .append("      background-color: #f5f5f5;")
                .append("      margin: 0;")
                .append("      padding: 0;")
                .append("    }")
                .append("")
                .append("    .container {")
                .append("      max-width: 600px;")
                .append("      margin: 0 auto;")
                .append("      background-color: #ffffff;")
                .append("      padding: 20px;")
                .append("      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);")
                .append("      border-radius: 5px;")
                .append("      margin-top: 30px;")
                .append("    }")
                .append("")
                .append("    h1 {")
                .append("      color: #003399;")
                .append("      font-size: 28px;")
                .append("      margin-bottom: 20px;")
                .append("      display: flex;")
                .append("      justify-content: center;")
                .append("    }")
                .append("")
                .append("    p {")
                .append("      font-size: 16px;")
                .append("      line-height: 1.5;")
                .append("      margin-bottom: 15px;")
                .append("    }")
                .append("")
                .append("    .button-outer {")
                .append("      display: flex;")
                .append("      justify-content: center !important;")
                .append("    }")
                .append("")
                .append("    .button {")
                .append("      display: inline-block;")
                .append("      background-color: #003399;")
                .append("      color: #ffffff !important;")
                .append("      padding: 10px 20px;")
                .append("      border-radius: 5px;")
                .append("      text-decoration: none;")
                .append("      font-size: 16px;")
                .append("      margin-top: 20px;")
                .append("    }")
                .append("")
                .append("    .button:hover {")
                .append("      background-color: #002266;")
                .append("    }")
                .append("")
                .append("    .logo {")
                .append("      display: block;")
                .append("      margin: 20px 0;")
                .append("    }")
                .append("")
                .append("    .footer {")
                .append("      margin-top: 30px;")
                .append("      font-size: 14px;")
                .append("      color: #999999;")
                .append("      text-align: center;")
                .append("    }")
                .append("")
                .append("    .footer a {")
                .append("      color: #999999;")
                .append("      text-decoration: none;")
                .append("    }")
                .append("")
                .append("    .footer a:hover {")
                .append("      text-decoration: underline;")
                .append("    }")
                .append("  </style>")
                .append("</head>")
                .append("")
                .append("<body>")
                .append("  <div class=\"container\">")
                .append("    <h1>Vet Registration Approved</h1>")
                .append("    <p>Dear ")
                .append(vetName)
                .append(",</p>")
                .append("    <p>We are pleased to inform you that your registration as a veterinarian with PawPals has been approved by our team.</p>")
                .append("    <p>Your account is now active and you can start using our platform to manage your veterinary practice. Please log in to your account to get started.</p>")
                .append("    <div class=\"button-outer\">")
                .append("      <a href=\"")
                .append(linkToLoginPage)
                .append("\" class=\"button\">Log In to Your Account</a>")
                .append("    </div>")
                .append("    <p>If you have any questions or concerns, please don't hesitate to contact us at <strong>support@pawpals.com</strong>.</p>")
                .append("    <div class=\"footer\">")
                .append("      <p>Thank you for choosing PawPals for your veterinary practice.</p>")
                .append("      <p>© PawPals 2023. All rights reserved.</p>")
                .append("    </div>")
                .append("  </div>")
                .append("</body>")
                .append("")
                .append("</html>").toString();
    }

    public static String getVetRejectedMessageString(String vetName) {
        return VET_REGISTRATION_REJECTED.append("<html>")
                .append("")
                .append("<head>")
                .append("  <title>PawPals - Vet Registration Approved</title>")
                .append("  <style>")
                .append("    body {")
                .append("      font-family: Arial, sans-serif;")
                .append("      background-color: #f5f5f5;")
                .append("      margin: 0;")
                .append("      padding: 0;")
                .append("    }")
                .append("")
                .append("    .container {")
                .append("      max-width: 600px;")
                .append("      margin: 0 auto;")
                .append("      background-color: #ffffff;")
                .append("      padding: 20px;")
                .append("      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);")
                .append("      border-radius: 5px;")
                .append("      margin-top: 30px;")
                .append("    }")
                .append("")
                .append("    h1 {")
                .append("      color: #003399;")
                .append("      font-size: 28px;")
                .append("      margin-bottom: 20px;")
                .append("      display: flex;")
                .append("      justify-content: center;")
                .append("    }")
                .append("")
                .append("    p {")
                .append("      font-size: 16px;")
                .append("      line-height: 1.5;")
                .append("      margin-bottom: 15px;")
                .append("    }")
                .append("")
                .append("    .button-outer {")
                .append("      display: flex;")
                .append("      justify-content: center;")
                .append("    }")
                .append("")
                .append("    .button {")
                .append("      display: inline-block;")
                .append("      background-color: #003399;")
                .append("      color: #ffffff;")
                .append("      padding: 10px 20px;")
                .append("      border-radius: 5px;")
                .append("      text-decoration: none;")
                .append("      font-size: 16px;")
                .append("      margin-top: 20px;")
                .append("    }")
                .append("")
                .append("    .button:hover {")
                .append("      background-color: #002266;")
                .append("    }")
                .append("")
                .append("    .logo {")
                .append("      display: block;")
                .append("      margin: 20px 0;")
                .append("    }")
                .append("")
                .append("    .footer {")
                .append("      margin-top: 30px;")
                .append("      font-size: 14px;")
                .append("      color: #999999;")
                .append("      text-align: center;")
                .append("    }")
                .append("")
                .append("    .footer a {")
                .append("      color: #999999;")
                .append("      text-decoration: none;")
                .append("    }")
                .append("")
                .append("    .footer a:hover {")
                .append("      text-decoration: underline;")
                .append("    }")
                .append("  </style>")
                .append("</head>")
                .append("")
                .append("<body>")
                .append("  <div class=\"container\">")
                .append("    <h1>Vet Registration Approved</h1>")
                .append("    <p>Dear ")
                .append(vetName)
                .append(",</p>")
                .append("    <p>We regret to inform you that your registration as a veterinarian with PawPals has been rejected by our team.</p>")
                .append("    <p>If you have any questions or concerns, please don't hesitate to contact us at <strong>support@pawpals.com</strong>.</p>")
                .append("    <div class=\"footer\">")
                .append("      <p>Thank you for choosing PawPals for your veterinary practice.</p>")
                .append("      <p>© PawPals 2023. All rights reserved.</p>")
                .append("    </div>")
                .append("  </div>")
                .append("</body>")
                .append("")
                .append("</html>").toString();
    }


    public static String getAppointmentConfirmationString(
            String petOwnerName,
            String appointmentDate,
            String appointmentTime,
            String appointmentLocation,
            String linktToLoginPage
    ) {
        return APPOINTMENT_CONFIRMATION.append("<html>")
                .append("<head>")
                .append("	<title>Pawpals - Appointment Registration Successful</title>")
                .append("	</head>")
                .append("  <style>")
                .append("    body {")
                .append("			font-family: Arial, sans-serif;")
                .append("			color: #333333;")
                .append("			background-color: #F2F2F2;")
                .append("			margin: 0;")
                .append("			padding: 0;")
                .append("		}")
                .append("		.container {")
                .append("			max-width: 600px;")
                .append("			margin: 0 auto;")
                .append("			padding: 20px;")
                .append("			background-color: #FFFFFF;")
                .append("			border-radius: 10px;")
                .append("			box-shadow: 0 0 10px rgba(0,0,0,0.1);")
                .append("		}")
                .append("		h1 {")
                .append("			font-size: 24px;")
                .append("			font-weight: bold;")
                .append("			margin-top: 0;")
                .append("			text-align: center;")
                .append("			color: #003399;")
                .append("		}")
                .append("		p {")
                .append("			font-size: 16px;")
                .append("			line-height: 1.5;")
                .append("			margin-bottom: 20px;")
                .append("		}")
                .append(".button-outer {")
                .append("      display: flex;")
                .append("      justify-content: center;")
                .append("    }")
                .append("		.btn {")
                .append("			display: inline-block;")
                .append("			padding: 10px 20px;")
                .append("			font-size: 16px;")
                .append("			font-weight: bold;")
                .append("			text-align: center;")
                .append("			text-decoration: none;")
                .append("			background-color: #003399;")
                .append("      ")
                .append("			color: #FFFFFF;")
                .append("			border-radius: 5px;")
                .append("			transition: all 0.3s ease;")
                .append("		}")
                .append("		.btn:hover {")
                .append("			background-color: #3C8D6E;")
                .append("			color: #FFFFFF;")
                .append("		}")
                .append("		.footer {")
                .append("			font-size: 14px;")
                .append("			color: #999999;")
                .append("			text-align: center;")
                .append("			margin-top: 20px;")
                .append("			padding-top: 20px;")
                .append("			border-top: 1px solid #CCCCCC;")
                .append("		}")
                .append("		.footer p {")
                .append("			margin: 0;")
                .append("			padding: 0;")
                .append("		}")
                .append("  </style>")
                .append("<body>")
                .append("	<div class=\"container\">")
                .append("		<h1>Appointment Registration Successful</h1>")
                .append("		<p>Dear ")
                .append(petOwnerName)
                .append(",</p>")
                .append("		<p>Thank you for scheduling an appointment with Pawpals. Your appointment has been successfully registered. Please check the details below:</p>")
                .append("		<ul>")
                .append("			<li><strong>Date:</strong> ")
                .append(appointmentDate)
                .append("</li>")
                .append("			<li><strong>Time:</strong> ")
                .append(appointmentTime)
                .append("</li>")
                .append("			<li><strong>Location:</strong> ")
                .append(appointmentLocation)
                .append("</li>")
                .append("		</ul>")
                .append("		<p>If you need to make any changes to your appointment or have any questions, please do not hesitate to contact us at <strong>support.pawpals@gmail.com</strong>.</p>")
                .append("    <div class=\"button-outer\">")
                .append("      <a href=\"")
                .append(linktToLoginPage)
                .append("\" class=\"btn\">View Appointment Details</a>")
                .append("    </div>")
                .append("		")
                .append("		<p>Best regards,</p>")
                .append("		<p>The Pawpals Team</p>")
                .append("		<div class=\"footer\">")
                .append("			<p>You are receiving this email because you registered for an appointment on Pawpals. If you did not register for an appointment, please ignore this email.</p><br>")
                .append("          <p>© PawPals 2023. All rights reserved.</p>")
                .append("		</div>")
                .append("	</div>")
                .append("</body>")
                .append("</html>").toString();
    }

    public static String getAppointmentCancelString(String petOwnerName, String appointmentDate, String appointmentTime) {
        return APPOINTMENT_CANCEL
                .append("<html>")
                .append("")
                .append("<head>")
                .append("  <meta charset=\"UTF-8\">")
                .append("  <title>PawPals - Appointment Cancellation Confirmation</title>")
                .append("  <style>")
                .append("    body {")
                .append("      font-family: Arial, sans-serif;")
                .append("      background-color: #f5f5f5;")
                .append("      margin: 0;")
                .append("      padding: 0;")
                .append("    }")
                .append("")
                .append("    .container {")
                .append("      max-width: 600px;")
                .append("      margin: 0 auto;")
                .append("      background-color: #ffffff;")
                .append("      padding: 20px;")
                .append("      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);")
                .append("      border-radius: 5px;")
                .append("      margin-top: 30px;")
                .append("    }")
                .append("")
                .append("    h1 {")
                .append("      color: #003399;")
                .append("      font-size: 28px;")
                .append("      margin-bottom: 20px;")
                .append("      display: flex;")
                .append("      justify-content:center;")
                .append("    }")
                .append("")
                .append("    p {")
                .append("      font-size: 16px;")
                .append("      line-height: 1.5;")
                .append("      margin-bottom: 15px;")
                .append("    }")
                .append("")
                .append("    .button-outer {")
                .append("      display: flex;")
                .append("      justify-content: center;")
                .append("    }")
                .append("")
                .append("    .button {")
                .append("      display: inline-block;")
                .append("      background-color: #003399;")
                .append("      color: #ffffff;")
                .append("      padding: 10px 20px;")
                .append("      border-radius: 5px;")
                .append("      text-decoration: none;")
                .append("      font-size: 16px;")
                .append("      margin-top: 20px;")
                .append("    }")
                .append("")
                .append("    .button:hover {")
                .append("      background-color: #002266;")
                .append("    }")
                .append("")
                .append("    .footer {")
                .append("      font-size: 14px;")
                .append("      color: #999999;")
                .append("      text-align: center;")
                .append("      margin-top: 20px;")
                .append("      padding-top: 20px;")
                .append("      border-top: 1px solid #CCCCCC;")
                .append("    }")
                .append("")
                .append("    .footer p {")
                .append("      margin: 0;")
                .append("      padding: 0;")
                .append("    }")
                .append("  </style>")
                .append("</head>")
                .append("")
                .append("<body>")
                .append("  <div class=\"container\">")
                .append("    <h1> Appointment cancelled</h1>")
                .append("    <p>Dear ")
                .append(petOwnerName)
                .append(",</p>")
                .append("    <p>This is to confirm that your pet's appointment with our veterinarian on <strong>")
                .append(appointmentDate)
                .append("</strong> at <strong>")
                .append(appointmentTime)
                .append("</strong> has been cancelled.</p>")
                .append("    <p>We apologize for any inconvenience this may have caused and hope that you will consider rescheduling your appointment in the future.</p>")
                .append("    <p>If you have any questions or concerns, please don't hesitate to contact us at <strong>[Email Address]</strong>.</p>")
                .append("    <div class=\"button-outer\">")
                .append("      <a href=\"[Link to Appointment Booking Page]\" class=\"button\">Book a New Appointment</a>")
                .append("    </div>")
                .append("    <p>Thank you for choosing PawPals for your pet's veterinary care.</p>")
                .append("    <p>Sincerely,</p>")
                .append("    <p>The PawPals Team</p>")
                .append("    <div class=\"footer\">")
                .append("      <p>You are receiving this email because you cancelled an appointment on Pawpals. If you did not cancelled an appointment, please ignore this email.</p><br>")
                .append("      <p>© PawPals 2023. All rights reserved.</p>")
                .append("    </div>")
                .append("  </div>")
                .append("</body>")
                .append("")
                .append("</html>").toString();
    }
}
